オブジェクト指向版のlsコマンドを作成した
kazubuntu/ruby-practices pull request #12
Opened 2023-05-23 01:31 UTC by kazubuntu

2023-05-28 16:11 UTC, u1tnk requested changes
実質メイクラスとファイル情報しかクラスが無く、メインクラスの責務が多過ぎるようです。
基本的なクラスの使い方などはできているし、FileStatisticsは概ね良さそうなので、メイン処理の分割を考えてみてください。

2023-05-28 16:11 UTC, u1tnk commented on 07.ls_object/file_statistics.rb
> +    @stat = File.lstat(directory_entry)
statだけあれば他のものは情報を取り出すだけなので、インスタンス変数に保存せず、メソッドが呼ばれたときに参照するようにした方がスッキリしますね。(もしくは `@stat` に移譲するのも良いです)

2023-05-28 16:11 UTC, u1tnk commented on 07.ls_object/directory_entry.rb
> +class DirectoryEntry
このクラスはどういう役割なのでしょうか？
このコードだけ見ると FileStatisticsと持っている情報が変わらないように見えます。

2023-05-29 13:57 UTC, kazubuntu commented on 07.ls_object/file_statistics.rb
> +    @stat = File.lstat(directory_entry)
インスタンス変数ではなく、メソッドで返すようにしました。

2023-05-29 13:59 UTC, kazubuntu commented on 07.ls_object/directory_entry.rb
> +class DirectoryEntry
ディレクトリはディレクトリエントリを持ってて、ディレクトリエントリは統計情報を持ってる、と考えてそれぞれをオブジェクトしたのですが、意味のないクラスになってしまっていました。
ディレクトリエントリクラスで統計情報を返すように変更しました。

2023-05-29 15:18 UTC, u1tnk requested changes
役割の分割方針は良いと思います！

- Terminalにformatterにあるべき機能もある。
- list_formatter がただのメソッド集になってしまっている。 long/shortを別クラスにするか initializeで optionとディレクトリ情報関係をもらって、共通のメソッド(to_sとか formatなど)を実行するとoptionによってフォーマットが変わるようにすると良いですね。

2023-05-30 14:03 UTC, u1tnk approved these changes
formatは文字列化なので文字列リストを返してるのがちょっと微妙ですが、まあフォーマット済みの文字列リストを作るものと解釈すればアリかなと思ったので良いかなと思いました。

2023-05-30 14:09 UTC, merged